### ISSUE TITLE
Support interfaces

### ISSUE THREAD

**Issue by simPod** [spawnia/sailor#35]
I'm trying to generate classes for InterfaceType and it seems not to be supported in ClassGenerator. Is it intentional?

selection is like

```gql
interfacetype {
    somefield
}
```

but I'm crashing on https://github.com/spawnia/sailor/blob/77ba1451bdc80126214af855af331f32f0694f51/src/Codegen/ClassGenerator.php#L251

>  Unsupported type GraphQL\Type\Definition\InterfaceType found.

Thanks

**Comment by spawnia** [comment]
Yeah, interfaces are not supported yet. I will probably add support as soon as I have a use case for them.

If you want to contribute, I am open to reviewing and aiding in the implementation of this feature.

**Comment by simPod** [comment]
Hmm. So what if we add methods to generated classes that represent Object types and let them implement interfaces representing Interface types for shared fields?

**Comment by spawnia** [comment]
The generated result objects allow access to fields in the form of properties. I think this is more elegant than methods because:
- it allows null-safe access with `??` (this will be less imporant with PHP 8 null safe method calls `?->`)
- no need to type an extra set of parantheses
- easy setup of mocked results for test by just setting the properties

That said, interfaces without methods still provide value:
- while they cannot define properties, they can indeed define virtual properties via `@property`. We will have to check how this interacts when the implementing object type narrows a field type, e.g. changing it to be non-nullable
- it can be used as a strong type hint

**Comment by simPod** [comment]
I see the PR, just few notes on those interfaces.

> easy setup of mocked results for test by just setting the properties

methods would read properties so the same applies, no?

> it allows null-safe access with `??`

method calls do so? or I don't understand

------------

Implemented interfaces only with properties seem a bit dirty as it is not how the language was designed

**Comment by spawnia** [comment]
Given this code:

```php
class Foo {
    public ?Foo $bar;
    function bar(): ?Foo { return null; }
}

$foo = new Foo;
```

The following will work without error:

```php
$foo->bar->bar ?? null;
```

This will throw with `Fatal error: Uncaught Error: Call to undefined function bar()`:

```php
$foo-bar()->bar() ?? null;
```

**Comment by simPod** [comment]
Ah ok I see what you meant by that. I go with PHP 8 everywhere.
