### ISSUE TITLE
Fire events

### ISSUE THREAD

**Issue by simbig** [spawnia/sailor#61]
**Is your feature request related to a problem? Please describe.**

I use https://github.com/itsgoingd/clockwork to debug my app. Clockwork keeps track of all triggered events including parameters. In many use cases it would be nice if the sailor actions were accessible as an event.

**Describe the solution you'd like**

add https://github.com/illuminate/events as a dependency and fire on execute and receivedResponse

**Comment by spawnia** [comment]
https://github.com/illuminate/events is quite a heavy dependency, because it relies on further Laravel components. https://www.php-fig.org/psr/psr-14 would be a framework agnostic alternative, but unfortunately is not adopted by Laravel.

I would tend towards adding a simple functional interface which allows for composition with frameworks.
